### ISSUE TITLE
Enable Kerberos for Trino on EMR

### ISSUE THREAD

**Issue by varunrao** [aws-samples/aws-emr-apache-ranger#31]
Trino (PrestoSQL) on EMR currenlty does not support Kerberos. Enabling this will allow the Presto Ranger plugin to work securely with strong Authentication (alternate is LDAP Auth for Presto).

**Comment by PRanderia** [comment]
Hi Varun,
Please prioritize this. I am running manual bootstrap script provided by AWS to kerberize Presto on EMR Release 5.29.0.

The same script does not work for Release 5.32 so I can't make use of AWS supported Ranger till we fix this issue.

Thanks
Paresh Randeria

**Comment by varunrao** [comment]
Paresh, thanks for helping us priortize this issue. Can you share the script you were using for EMR 5.29? We are actively working on this and additionally 6.X + PrestoSQL support as well.

**Comment by PRanderia** [comment]
Hi Varun,

Sure. Thanks.

It is the scripts developed by one of your AWS engineer: https://gist.github.com/jbenninghoff/5ee441f2c549f0ec6a3ece57e2912a40

I am using following scripts, of course provided by AWS technical engineer. 

presto-kerberos-tls.sh
hue_impersonation_presto.sh

Do you want me attached scripts here? or would like to email it you privately?

**Comment by varunrao** [comment]
Hi Paresh,
I have made an update that to V2 which has the basic code to support Presto Kerberos on V5.29. Working with the team internally to this is this 5.32 as well

**Comment by PRanderia** [comment]
Hi Varun,

Great. Please let me know you have the working script for the EMR Release 5.32. I hope same script will work for EMR Release 6.2.0 too.
In my case the EMR creation failed or does not installed Presto. Unfortunately, EMR is immediately terminated and I don't have an access to see the logs.

Appreciate your prompt response and action.
