### ISSUE TITLE
STEP0AMILookup fails if a default vpc isn't present in AWS Account

### ISSUE THREAD

**Issue by anuragrawat28** [aws-samples/aws-emr-apache-ranger#39]
The nested stack for STEP0AMILookup fails if default VPC is not present for AWS Account for Resource **SampleInstance** in **lambda-amilookup-win.template** template (line number 91).
Ideally it should take additional parameters of VPC and subnet for **SampleInstance** if default VPC does not exist.
As per my understanding SampleInstance is just to check if AMI can be used or not, for moving forward I have removed **SampleInstance** resource from the template.
[lambda-amilookup-win.txt](https://github.com/aws-samples/aws-emr-apache-ranger/files/5951232/lambda-amilookup-win.txt)

**Comment by varunrao** [comment]
You are right, SampleInstance can cause this issue. It is not needed for the AMI lookup code. I will move as a defect

**Comment by archit-cloud** [comment]
@varunrao 
@anuragrawat28 and me work together can we get one level of support from AWS for ranger  ? I have support subscription but not in that account where we are doing testing of Ranger + EMR

**Comment by varunrao** [comment]
We have removed the Lambda with the latest V3 release
