### ISSUE TITLE
Unable to create external table from hiveserver2(beeline)

### ISSUE THREAD

**Issue by archit-cloud** [aws-samples/aws-emr-apache-ranger#40]
We are trying to create external table from HS2 but it’s failing with the permission denied error.
The raw data location is s3
I have given all permission on s3 bucket and hive database in Ranger + S3 bucket have IAM Roles permission, which is assigned to EMR 

- I am able to get s3 file from Hadoop fs -get command 
- I am able to create table from hive CLI and able to execute all queries from hive CLI as well as hiveserver2

**Comment by anandkumarsk** [comment]
Can you verify whether you have permission in the database, that you are trying to create your table into? if you are creating in "default", you should have permission to default database as well.

**Comment by archit-cloud** [comment]
Yes I have full permission on database, but still I am facing the permission issue 
Give me sometime I will provide you the screenshots

**Comment by archit-cloud** [comment]
Below is the execption that we are facing: 
Error: Error while compiling statement: FAILED: HiveAccessControlException Permission denied: user [archit] does not have [READ] privilege on [s3://{bucket-name}/user/AutomationFiles/Gantt/Product] (state=42000,code=40000)

In Ranger the user have full permission on s3 bucket

**Comment by varunrao** [comment]
This is a hive error tied to the hive plugin not the S3 plugin. Under hive
you will need to specify access to the S3 location using the URI property
Search for URI in the link below.

https://docs.cloudera.com/HDPDocuments/HDP3/HDP-3.0.0/authorization-ranger/content/resource_policy_create_a_hive_policy.html

**Comment by archit-cloud** [comment]
Thanks @varunrao,
URL was available but "**s3://**" was missing in my URL
I worked after adding s3:// in URL
thanks for your help 👍
