### ISSUE TITLE
LaunchEMRClusterFunction fails due to python3.6 is no longer supported

### ISSUE THREAD

**Issue by ironpe** [aws-samples/aws-emr-apache-ranger#78]
During the step [EMRSecurityWithRangerBlogV3-Step2-EMRCluster], below error occurs:
Resource handler returned message: "The runtime parameter of python3.6 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (python3.9) while creating or updating functions.

**Comment by varunrao** [comment]
Thank you for opening this issue. the master branch should have these changes.
