### ISSUE TITLE
RangerInstance Type fixed to be r5.2xlarge as an output Ranger instance type from using the CloudFormation Template: step2_ranger-rds-emr.template

### ISSUE THREAD

**Issue by heng2j** [aws-samples/aws-emr-apache-ranger#97]
Hi Team,

Thank you for the wonderful work here to push the native AWS EMR Ranger support.

I noticed that by running the [step2_ranger-rds-emr.template](https://console.aws.amazon.com/cloudformation/home?region=us-east-1#/stacks/new?stackName=EMRSecurityWithRangerBlogV3-Step2&templateURL=https://s3.amazonaws.com/aws-bigdata-blog/artifacts/aws-blog-emr-ranger/3.0/cloudformation/step2_ranger-rds-emr.template), despited I am setting RangerInstanceType = m4.large. Turns out it is still created the Ranger instance with r5.2xlarge. And I do not have any issue for other parameters. 

Can you advise?

Thank you,
Heng

**Comment by heng2j** [comment]
I found the workaround by creating my own version of [ranger-server.template](https://s3.amazonaws.com/aws-bigdata-blog/artifacts/aws-blog-emr-ranger/3.0/cloudformation/ranger-server.template ). 

But still want to leave this issue open for the bug that we have in the [step2_ranger-rds-emr.template](https://console.aws.amazon.com/cloudformation/home?region=us-east-1#/stacks/new?stackName=EMRSecurityWithRangerBlogV3-Step2&templateURL=https://s3.amazonaws.com/aws-bigdata-blog/artifacts/aws-blog-emr-ranger/3.0/cloudformation/step2_ranger-rds-emr.template)  I am able to find the proper config

**Comment by varunrao** [comment]
Thanks for submitting the issue. We have pushed this change to the master branch - for blog_v3
